apiVersion: v1
kind: ReplicationController
metadata:
  name: csats-balancer
  labels:
    app: csats-balancer
spec:
  replicas: 1
  selector:
    app: csats-balancer
  template:
    metadata:
      labels:
        app: csats-balancer
    spec:
      containers:
      - image: docker.io/csats/csats-balancer:0.1
        imagePullPolicy: Always
        name: csats-balancer
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
